name = "PumasPublicRegistry"
uuid = "520a0f63-b2d4-4225-8b9a-7f2e3b94dc7e"
repo = "https://github.com/PumasAI/PumasPublicRegistry.git"

[packages]
1ad3e620-8996-5565-b8b0-a1489189912b = { name = "BundleLoader_jll", path = "jll/B/BundleLoader_jll" }
