name: Registry Consistency
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags: '*'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: read
jobs:
  finalize:
    timeout-minutes: 10
    needs: [consistency]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo consistency: ${{ needs.consistency.result }}
      - run: exit 1
        if: |
          contains('failure cancelled', needs.consistency.result)

  consistency:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.10'
          - '1'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: ${{ matrix.julia-version }}
      - name: Instantiate and precompile the .ci environment
        run: |
          import Pkg
          Pkg.instantiate()
          Pkg.precompile()
        shell: julia --project=.ci --color=yes {0}
      - name: Run the registry consistency tests (RegistryCI.test)
        run: |
          import RegistryCI
          const general_registry_url = "https://github.com/JuliaRegistries/General"
          const registry_deps = [general_registry_url]
          const registry_path = pwd()
          @info "" registry_path registry_deps
          RegistryCI.test(registry_path; registry_deps)
        shell: julia --project=.ci --color=yes {0}
        env:
          JULIA_LOAD_PATH: '@'
